/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menugps.interfacegrafica;

import javax.swing.JOptionPane;
import menugps.VariaveisGlobais;
import static sun.lwawt.macosx.CWrapper.NSView.frame;

/**
 *
 * @author joaopinho
 */
public class Temporizador extends javax.swing.JFrame {

    public Temporizador() {
        initComponents();
        this.setVisible(true);
        this.setLocation(300, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textHoras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textMinutos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textSeg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notasProjeto = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tituloProjeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setText("ProGest");

        jLabel2.setText("Tempo desejado para terminar projeto:");

        textHoras.setText("00");
        textHoras.setToolTipText("");
        textHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHorasActionPerformed(evt);
            }
        });
        textHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textHorasKeyPressed(evt);
            }
        });

        jLabel3.setText("Horas:");

        jLabel4.setText("Minutos:");

        textMinutos.setText("00");
        textMinutos.setSize(new java.awt.Dimension(84, 28));
        textMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMinutosActionPerformed(evt);
            }
        });

        jLabel5.setText("Segundos:");

        textSeg.setText("00");
        textSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSegActionPerformed(evt);
            }
        });

        notasProjeto.setColumns(20);
        notasProjeto.setRows(5);
        jScrollPane1.setViewportView(notasProjeto);

        jLabel6.setText("Descrição:");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Titulo do projeto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jButton1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(textHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(textMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addComponent(tituloProjeto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSegActionPerformed

    private void textMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMinutosActionPerformed

    private void textHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHorasActionPerformed

    }//GEN-LAST:event_textHorasActionPerformed

    private void textHorasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textHorasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHorasKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean inteiros = true;
        String erro = "";

        try {
            Integer.parseInt(textHoras.getText());
            Integer.parseInt(textMinutos.getText());
            Integer.parseInt(textSeg.getText());

            if (Integer.parseInt(textMinutos.getText()) > 59 || Integer.parseInt(textMinutos.getText()) < 0) {
                inteiros = false;
                erro = "Minutos tem de estar entre 0 e 59";
            }
            if (Integer.parseInt(textSeg.getText()) > 59 || Integer.parseInt(textMinutos.getText()) < 0) {
                inteiros = false;
                erro = "Segundos tem de estar entre 0 e 59";
            }
            if(tituloProjeto.getText().isEmpty()){
                inteiros = false;
                erro = "Precisa de inserir um título";
            }
            if(notasProjeto.getText().isEmpty()){
                inteiros = false;
                erro = "Precisa de inserir uma descrição";
            }
        } catch (NumberFormatException e) {
            inteiros = false;
            erro = "Horas, Minutos e Segundos têm de ser numeros inteiros!";
        }

        if (inteiros == true) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new CountTimerGUI(Integer.parseInt(textHoras.getText()), Integer.parseInt(textMinutos.getText()), Integer.parseInt(textSeg.getText()));
                }
            });

            VariaveisGlobais.notas.setTitulo(tituloProjeto.getText());
            VariaveisGlobais.notas.setDescricao(notasProjeto.getText());

            Notas n = new Notas();
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, erro, "Dados Inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temporizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temporizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temporizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temporizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temporizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea notasProjeto;
    private javax.swing.JTextField textHoras;
    private javax.swing.JTextField textMinutos;
    private javax.swing.JTextField textSeg;
    private javax.swing.JTextField tituloProjeto;
    // End of variables declaration//GEN-END:variables
}
